name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'
      - '**.tf'

jobs:
  plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      tf_command: plan
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  apply:
    name: Terraform Apply
    needs: plan
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      tf_command: apply
      environment_name: production
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}