name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Terraform Destroy
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      tf_command: destroy
      environment_name: production
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}